### ISSUE TITLE
Fail to install under go version 1.17

### ISSUE THREAD

**Issue by GeromeRen** [hashicorp/terraform-config-inspect#87]
Environment: go 1.17.0 x64

We are using windows-latest hosted agent in AzureDevOps. During pipeline execution, it fail to install terraform-config-inspect using go 1.17, however it works in go 1.18. 

Below is the error message using go 1.17:

go version go1.17 windows/amd64
Cloning into 'terraform-config-inspect'...
go: downloading github.com/spf13/pflag v1.0.3
go: downloading github.com/hashicorp/hcl v0.0.0-20170504190234-a4b07c25de5f
go: downloading github.com/hashicorp/hcl/v2 v2.0.0
go: downloading github.com/zclconf/go-cty v1.1.0
go: downloading github.com/agext/levenshtein v1.2.2
go: downloading github.com/apparentlymart/go-textseg v1.0.0
go: downloading github.com/mitchellh/go-wordwrap v1.0.0
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/google/go-cmp v0.3.0
# github.com/hashicorp/terraform-config-inspect/tfconfig
tfconfig\filesystem.go:93:37: undefined: any
note: module requires Go 1.18

May I ask whether terraform-config-inspect still support install under go 1.17?

**Comment by karedinvs** [comment]
have the same question
Does the library support setting version like this
github.com/hashicorp/terraform-config-inspect@VERSION
